### CREATE SMALL LIBERTY IMAGE ###
FROM icr.io/appcafe/open-liberty:kernel-slim-java11-openj9-ubi as buildLiberty_minify

ARG CONFIG_DIRECTORY

# Install unzip; needed to unzip Open Liberty
USER 0
RUN yum -y install unzip
USER 1001

# Copy in a server.xml to start server with correct features set
COPY --chown=1001:0 ${CONFIG_DIRECTORY} /config
RUN features.sh

# Create a minified openliberty package for use in final image
RUN /opt/ol/wlp/bin/server package --archive=/tmp/ol_minified.zip --include=minify --os=Linux

WORKDIR /tmp

RUN unzip -q /tmp/ol_minified.zip -d /tmp/ol

### CREATE SMALL JRE IMAGE ###
FROM ibmsemeruruntime/open-11-jdk:ubi-jdk as buildjre

COPY --chown=1001:0 jdeps/java_modules.txt /tmp

RUN /opt/java/openjdk/bin/jlink --no-header-files \
           --no-man-pages --compress=2 \
           --strip-debug \
           --add-modules $(cat /tmp/java_modules.txt) \
           --output /opt/jdk11-minified

### CREATE BASE SCC LAYER ###
FROM registry.access.redhat.com/ubi8/ubi-minimal as buildscc

RUN mkdir -p /output/workarea && mkdir -p /output/.classCache \
    && chown -R 1001:0 /output && chmod -R g+rw /output 

USER 1001

ARG CONFIG_DIRECTORY

# copy in the minified java11 jre
COPY --chown=1001:0 --from=buildjre /opt/jdk11-minified /opt/jdk11-minified

# copy in the minified package of open liberty
COPY --chown=1001:0 --from=buildLiberty_minify /tmp/ol /opt/ol/
COPY --chown=1001:0 --from=buildLiberty_minify /opt/ol/helpers/build/populate_scc.sh /opt/ol/helpers/build/populate_scc.sh

# Config
COPY --chown=1001:0 ${CONFIG_DIRECTORY}/* /opt/ol/wlp/usr/servers/defaultServer/

ENV JAVA_HOME=/opt/jdk11-minified

# Run populate_scc.sh script
ENV PATH=/opt/ol/wlp/bin:/opt/ol/helpers/build:/opt/jdk11-minified/bin:$PATH
ARG VERBOSE=true
RUN populate_scc.sh -i 1

### FINAL BASE IMAGE ###
FROM registry.access.redhat.com/ubi8/ubi-minimal

RUN mkdir -p /output/workarea && mkdir -p /output/.classCache \
    && chown -R 1001:0 /output && chmod -R g+rw /output 

USER 1001

ARG CONFIG_DIRECTORY

# copy in the minified java11 jre
COPY --chown=1001:0 --from=buildjre /opt/jdk11-minified /opt/jdk11-minified

# copy in the minified package of open liberty
COPY --chown=1001:0 --from=buildLiberty_minify /tmp/ol /opt/ol/
COPY --chown=1001:0 --from=buildLiberty_minify /opt/ol/helpers/build/populate_scc.sh /opt/ol/helpers/build/populate_scc.sh

# copy in the populated SCC from build_scc
COPY --chown=1001:0 --from=buildscc /output/.classCache /output/.classCache

# Config
COPY --chown=1001:0 ${CONFIG_DIRECTORY}/* /opt/ol/wlp/usr/servers/defaultServer/

ENV PATH=/opt/ol/wlp/bin:/opt/ol/helpers/build:/opt/jdk11-minified/bin:$PATH
ENV JAVA_HOME=/opt/jdk11-minified
ENV OPENJ9_JAVA_OPTIONS="-XX:+IgnoreUnrecognizedVMOptions -XX:+IdleTuningGcOnIdle -Xshareclasses:name=liberty,readonly,cacheDir=/output/.classCache -Dosgi.checkConfiguration=false"

CMD ["/opt/ol/wlp/bin/server", "run", "defaultServer"]
